export const productsData = [
  {
    id: 1,
    title: "volutpat",
    price: "$66.58",
    size: ["x", "xl", "xxl"],
    quantity: 1,
  },
  { id: 2, title: "sit", price: "$57.29", size: ["xl", "l"], quantity: 1 },
  {
    id: 3,
    title: "sapien",
    price: "$75.65",
    size: ["x", "l"],
    quantity: 1,
  },
  {
    id: 4,
    title: "eget",
    price: "$19.36",
    size: ["x", "xl", "xxl"],
    quantity: 1,
  },
  {
    id: 5,
    title: "metus",
    price: "$29.79",
    size: ["l"],
    quantity: 1,
  },
  {
    id: 6,
    title: "bibendum",
    price: "$72.95",
    size: ["l"],
    quantity: 1,
  },
  {
    id: 7,
    title: "erat",
    price: "$79.92",
    size: ["x"],
    quantity: 1,
  },
  { id: 8, title: "leo", price: "$97.95", size: ["xl"], quantity: 1 },
  { id: 9, title: "id", price: "$68.61", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 10,
    title: "nibh",
    price: "$50.33",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 11,
    title: "non",
    price: "$32.14",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 12,
    title: "justo",
    price: "$33.90",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 13,
    title: "morbi",
    price: "$60.32",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 14,
    title: "dis",
    price: "$86.84",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 15, title: "in", price: "$42.31", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 16,
    title: "commodo",
    price: "$70.06",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 17,
    title: "nulla",
    price: "$94.43",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 18,
    title: "aenean",
    price: "$30.43",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 19,
    title: "duis",
    price: "$83.94",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 20,
    title: "tristique",
    price: "$59.18",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 21,
    title: "eget",
    price: "$73.72",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 22,
    title: "lobortis",
    price: "$22.74",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 23,
    title: "quisque",
    price: "$74.21",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 24,
    title: "volutpat",
    price: "$18.78",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 25,
    title: "adipiscing",
    price: "$48.64",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 26,
    title: "scelerisque",
    price: "$43.60",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 27,
    title: "nec",
    price: "$46.27",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 28,
    title: "est",
    price: "$28.28",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 29,
    title: "non",
    price: "$75.16",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 30,
    title: "nec",
    price: "$63.62",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 31,
    title: "sollicitudin",
    price: "$82.80",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 32, title: "in", price: "$98.59", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 33,
    title: "curabitur",
    price: "$82.22",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 34,
    title: "ultrices",
    price: "$56.82",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 35,
    title: "quam",
    price: "$51.27",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 36,
    title: "vestibulum",
    price: "$68.78",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 37,
    title: "elit",
    price: "$79.79",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 38,
    title: "sagittis",
    price: "$60.76",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 39,
    title: "aliquet",
    price: "$81.09",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 40,
    title: "nunc",
    price: "$42.05",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 41, title: "in", price: "$35.99", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 42,
    title: "odio",
    price: "$58.84",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 43,
    title: "non",
    price: "$57.90",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 44,
    title: "potenti",
    price: "$86.52",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 45,
    title: "cursus",
    price: "$13.94",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 46,
    title: "aenean",
    price: "$73.66",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 47,
    title: "fermentum",
    price: "$22.25",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 48,
    title: "pharetra",
    price: "$69.32",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 49,
    title: "aliquet",
    price: "$80.61",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 50,
    title: "vehicula",
    price: "$21.26",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 51,
    title: "pretium",
    price: "$31.73",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 52,
    title: "tempus",
    price: "$26.77",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 53, title: "ut", price: "$64.02", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 54,
    title: "nullam",
    price: "$44.80",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 55,
    title: "eget",
    price: "$86.26",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 56,
    title: "lacus",
    price: "$53.54",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 57,
    title: "rutrum",
    price: "$44.94",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 58,
    title: "molestie",
    price: "$40.34",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 59,
    title: "sapien",
    price: "$30.33",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 60,
    title: "enim",
    price: "$36.30",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 61, title: "mi", price: "$53.12", size: ["x", "xl", "l"], quantity: 1 },
  { id: 62, title: "ac", price: "$26.26", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 63,
    title: "varius",
    price: "$54.39",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 64,
    title: "lectus",
    price: "$42.96",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 65,
    title: "nibh",
    price: "$81.58",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 66,
    title: "sapien",
    price: "$63.95",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 67,
    title: "eget",
    price: "$78.86",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 68,
    title: "fusce",
    price: "$98.73",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 69,
    title: "maecenas",
    price: "$10.67",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 70, title: "id", price: "$18.12", size: ["x", "xl", "l"], quantity: 1 },
  { id: 71, title: "a", price: "$42.20", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 72,
    title: "vestibulum",
    price: "$68.90",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 73, title: "at", price: "$99.44", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 74,
    title: "dui",
    price: "$83.96",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 75,
    title: "risus",
    price: "$34.34",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 76,
    title: "tristique",
    price: "$34.00",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 77,
    title: "curabitur",
    price: "$42.04",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 78,
    title: "non",
    price: "$86.18",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 79,
    title: "semper",
    price: "$39.23",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 80,
    title: "sem",
    price: "$96.98",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 81, title: "in", price: "$30.04", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 82,
    title: "nisl",
    price: "$38.63",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 83,
    title: "amet",
    price: "$70.11",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 84, title: "in", price: "$51.16", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 85,
    title: "massa",
    price: "$71.27",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 86,
    title: "nibh",
    price: "$76.30",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 87,
    title: "cras",
    price: "$47.13",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 88,
    title: "magna",
    price: "$26.87",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 89,
    title: "curabitur",
    price: "$79.32",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  { id: 90, title: "ut", price: "$46.78", size: ["x", "xl", "l"], quantity: 1 },
  { id: 91, title: "mi", price: "$60.51", size: ["x", "xl", "l"], quantity: 1 },
  {
    id: 92,
    title: "mattis",
    price: "$10.53",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 93,
    title: "est",
    price: "$37.72",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 94,
    title: "sit",
    price: "$17.07",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 95,
    title: "ligula",
    price: "$31.51",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 96,
    title: "duis",
    price: "$65.18",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 97,
    title: "aliquet",
    price: "$98.97",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 98,
    title: "hendrerit",
    price: "$15.52",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 99,
    title: "venenatis",
    price: "$50.99",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
  {
    id: 100,
    title: "integer",
    price: "$93.29",
    size: ["x", "xl", "l"],
    quantity: 1,
  },
];
