export const productsData = [
  { id: 1, title: "mi", price: "$21.71", size: "XL", quantity: 1 },
  { id: 2, title: "maecenas", price: "$75.37", size: "3XL", quantity: 1 },
  { id: 3, title: "et magnis", price: "$62.46", size: "XS", quantity: 1 },
  { id: 4, title: "congue", price: "$31.77", size: "L", quantity: 1 },
  { id: 5, title: "id", price: "$44.38", size: "3XL", quantity: 1 },
  { id: 6, title: "viverra", price: "$73.50", size: "M", quantity: 1 },
  { id: 7, title: "duis", price: "$93.44", size: "L", quantity: 1 },
  { id: 8, title: "luctus", price: "$26.89", size: "3XL", quantity: 1 },
  {
    id: 9,
    title: "dictumst ",
    price: "$43.49",
    size: "2XL",
    quantity: 1,
  },
  { id: 10, title: "sapien ", price: "$53.69", size: "L", quantity: 1 },
  { id: 11, title: "est", price: "$91.74", size: "L", quantity: 1 },
  { id: 12, title: "quis", price: "$68.79", size: "S", quantity: 1 },
  {
    id: 13,
    title: "erat ",
    price: "$59.17",
    size: "3XL",
    quantity: 1,
  },
  { id: 14, title: "convallis", price: "$78.58", size: "M", quantity: 1 },
  { id: 15, title: " volutpat", price: "$61.53", size: "S", quantity: 1 },
  { id: 16, title: "erat", price: "$43.39", size: "2XL", quantity: 1 },
  { id: 17, title: " ultrices", price: "$29.68", size: "3XL", quantity: 1 },
  { id: 18, title: "fusce", price: "$63.27", size: "3XL", quantity: 1 },
  { id: 19, title: "quis", price: "$27.37", size: "S", quantity: 1 },
  { id: 20, title: "duis at", price: "$20.56", size: "S", quantity: 1 },
  { id: 21, title: "posuere", price: "$59.51", size: "XS", quantity: 1 },
  { id: 22, title: "turpis sed", price: "$66.70", size: "2XL", quantity: 1 },
  { id: 23, title: "justo", price: "$23.81", size: "M", quantity: 1 },
  { id: 24, title: "habitasse", price: "$29.18", size: "S", quantity: 1 },
  {
    id: 25,
    title: "convallis",
    price: "$49.72",
    size: "L",
    quantity: 1,
  },
  { id: 26, title: "faucibus", price: "$31.22", size: "XS", quantity: 1 },
  { id: 27, title: "tortor", price: "$78.44", size: "3XL", quantity: 1 },
  { id: 28, title: "cursus id", price: "$89.60", size: "XS", quantity: 1 },
  { id: 29, title: "risus", price: "$56.96", size: "3XL", quantity: 1 },
  { id: 30, title: "elementum", price: "$80.19", size: "XL" },
  { id: 31, title: "vel", price: "$14.83", size: "S", quantity: 1 },
  {
    id: 32,
    title: "praesent",
    price: "$39.59",
    size: "2XL",
    quantity: 1,
  },
  {
    id: 33,
    title: " aliquam",
    price: "$46.37",
    size: "3XL",
    quantity: 1,
  },
  {
    id: 34,
    title: "lobortis",
    price: "$15.41",
    size: "L",
    quantity: 1,
  },
  { id: 35, title: "in", price: "$59.40", size: "3XL", quantity: 1 },
  { id: 36, title: "nunc", price: "$13.57", size: "XS", quantity: 1 },
  { id: 37, title: "nibh", price: "$45.42", size: "3XL", quantity: 1 },
  { id: 38, title: " odio", price: "$80.26", size: "XL", quantity: 1 },
  { id: 39, title: "ut", price: "$79.16", size: "S", quantity: 1 },
  { id: 40, title: "sapien", price: "$93.05", size: "XL", quantity: 1 },
  { id: 41, title: "id", price: "$12.40", size: "M", quantity: 1 },
  { id: 42, title: "quam", price: "$98.32", size: "3XL", quantity: 1 },
  { id: 43, title: "nulla", price: "$45.14", size: "XL", quantity: 1 },
  { id: 44, title: "tortor", price: "$44.15", size: "3XL", quantity: 1 },
  { id: 45, title: "sed", price: "$13.75", size: "L", quantity: 1 },
  { id: 46, title: "at", price: "$24.97", size: "S", quantity: 1 },
  {
    id: 47,
    title: "fringilla",
    price: "$41.80",
    size: "XS",
    quantity: 1,
  },
  { id: 48, title: "nisl aenean", price: "$66.17", size: "S", quantity: 1 },
  { id: 49, title: "quam sapien", price: "$67.63", size: "2XL", quantity: 1 },
  { id: 50, title: "donec quis", price: "$93.28", size: "L", quantity: 1 },
  { id: 51, title: "id nisl", price: "$68.96", size: "XS", quantity: 1 },
  { id: 52, title: "luctus", price: "$70.94", size: "S", quantity: 1 },
  { id: 53, title: "nunc", price: "$55.44", size: "S", quantity: 1 },
  {
    id: 54,
    title: "pellentesque",
    price: "$50.59",
    size: "M",
    quantity: 1,
  },
  { id: 55, title: "id", price: "$68.70", size: "2XL", quantity: 1 },
  { id: 56, title: "luctus", price: "$29.92", size: "S", quantity: 1 },
  { id: 57, title: "id", price: "$60.62", size: "XL", quantity: 1 },
  { id: 58, title: "dictumst", price: "$44.50", size: "M", quantity: 1 },
  {
    id: 59,
    title: "ullamcorper",
    price: "$12.90",
    size: "XS",
    quantity: 1,
  },
  { id: 60, title: "eros", price: "$97.64", size: "S", quantity: 1 },
  {
    id: 61,
    title: "suspendisse",
    price: "$63.53",
    size: "2XL",
    quantity: 1,
  },
  { id: 62, title: "erat", price: "$65.49", size: "S", quantity: 1 },
  { id: 63, title: "ipsum primis", price: "$24.61", size: "M", quantity: 1 },
  { id: 64, title: "auctor", price: "$63.50", size: "M", quantity: 1 },
  { id: 65, title: "sapien a", price: "$52.07", size: "3XL", quantity: 1 },
  { id: 66, title: "ac neque", price: "$58.78", size: "S", quantity: 1 },
  { id: 67, title: "nisi", price: "$86.67", size: "XL", quantity: 1 },
  { id: 68, title: "tellus in", price: "$96.12", size: "M", quantity: 1 },
  { id: 69, title: "ac nibh", price: "$13.61", size: "L", quantity: 1 },
  { id: 70, title: "in libero", price: "$73.72", size: "L", quantity: 1 },
  { id: 71, title: "in", price: "$70.25", size: "XS", quantity: 1 },
  { id: 72, title: "orci vehicula", price: "$60.59", size: "XL", quantity: 1 },
  {
    id: 73,
    title: "interdum",
    price: "$22.20",
    size: "M",
    quantity: 1,
  },
  { id: 74, title: "ipsum dolor", price: "$50.42", size: "S", quantity: 1 },
  { id: 75, title: "morbi", price: "$91.97", size: "L", quantity: 1 },
  { id: 76, title: "quam", price: "$42.48", size: "L", quantity: 1 },
  { id: 77, title: "volutpat", price: "$74.25", size: "2XL", quantity: 1 },
  { id: 78, title: "nulla", price: "$37.78", size: "S", quantity: 1 },
  { id: 79, title: "viverra", price: "$16.10", size: "3XL", quantity: 1 },
  { id: 80, title: "volutpat", price: "$17.59", size: "XL", quantity: 1 },
  { id: 81, title: "vel", price: "$83.02", size: "3XL", quantity: 1 },
  { id: 82, title: "eget", price: "$75.17", size: "XL", quantity: 1 },
  { id: 83, title: "pellentesque", price: "$89.16", size: "XS", quantity: 1 },
  { id: 84, title: "morbi ut", price: "$12.71", size: "S", quantity: 1 },
  { id: 85, title: "urna", price: "$98.15", size: "L", quantity: 1 },
  { id: 86, title: "ut volutpat", price: "$75.36", size: "M" },
  { id: 87, title: "magna", price: "$89.17", size: "XL", quantity: 1 },
  { id: 88, title: "mauris non", price: "$56.97", size: "2XL", quantity: 1 },
  { id: 89, title: "mauris", price: "$31.96", size: "L", quantity: 1 },
  {
    id: 90,
    title: "posuere",
    price: "$63.98",
    size: "3XL",
    quantity: 1,
  },
  { id: 91, title: "proin", price: "$20.39", size: "M", quantity: 1 },
  { id: 92, title: "convallis", price: "$38.58", size: "L", quantity: 1 },
  { id: 93, title: "rutrum neque", price: "$48.62", size: "3XL", quantity: 1 },
  { id: 94, title: "congue etiam", price: "$56.73", size: "M", quantity: 1 },
  { id: 95, title: "leo", price: "$97.73", size: "M", quantity: 1 },
  {
    id: 96,
    title: "volutpat",
    price: "$78.65",
    size: "3XL",
    quantity: 1,
  },
  { id: 97, title: "morbi", price: "$75.36", size: "3XL", quantity: 1 },
  { id: 98, title: "nec dui", price: "$82.87", size: "S", quantity: 1 },
  { id: 99, title: "mi", price: "$20.99", size: "L", quantity: 1 },
  { id: 100, title: "et", price: "$91.67", size: "3XL", quantity: 1 },
];
